### ISSUE TITLE
将SPU做成本地应用

### ISSUE THREAD

**Issue by SteamFinder** [SPGoding/spu#47]
请问dalao需要吗？
示例https://pan.baidu.com/s/1MUO3fYo8QQoFY1OrBUsN6g
同MCBBS上shen_tou2014的信息

**Comment by SPGoding** [comment]
已在 MCBBS 回复

**Comment by SPGoding** [comment]
spu 已作为 npm 模块发布至 https://npmjs.com/package/spu，如果要做成桌面应用的话可以会更方便一些。
