### ISSUE TITLE
是否考虑使用更好的 snackbar

### ISSUE THREAD

**Issue by langyo** [SPGoding/spu#53]
https://material-ui.com/demos/snackbars/#notistack

https://github.com/iamhosseindhv/notistack

如果你同意，我会在两个月内向你这里提交 PR

@SPGoding

**Comment by langyo** [comment]
最近有点忙，等抽出时间我会做的……

@SPGoding

**Comment by SPGoding** [comment]
重新写了一套 UI 别打我【跑

这个仓库变成一个 npm package 了，UI 移动到了 https://github.com/SPGoding/spu-angular
