### ISSUE TITLE
/give命令转换错误

### ISSUE THREAD

**Issue by Voidcrystal** [SPGoding/spu#6]
在1.12.2下，给予一本修复的附魔书命令为
/give @p minecraft:enchanted_book 1 0 {StoredEnchantments:[{id:70s,lvl:1s}]}
使用spu转换后为
/give @p minecraft:enchanted_book{Enchantments:[{id:"minecraft:mending",lvl:1s}]} 1
这样得到的附魔书无法使用
实际命令应为
/give @p minecraft:enchanted_book{StoredEnchantments:[{id:"minecraft:mending",lvl:1s}]} 1

**Comment by SPGoding** [comment]
小失误…会修的…
