### ISSUE TITLE
关于ID变更的问题

### ISSUE THREAD

**Issue by sheep-realms** [SPGoding/spu#94]
输入1.8命令：
```execute @a ~ ~ ~ detect ~ ~ ~ minecraft:grass -1 kill @e```
输出1.14命令：
```execute as @a at @s if block ~ ~ ~ minecraft:grass run kill @e```

然而草方块在新版本中已经改名为**minecraft:grass_block**，所以要不要考虑考虑加入ID的变更呢 : P

**Comment by SPGoding** [comment]
问题不在方块 ID 变更，而是在数据值指定为了 `-1`。如果将数据值修改为 `0` 或其他合法的方块状态对则没有任何问题。例如：

`execute @a ~ ~ ~ detect ~ ~ ~ minecraft:grass 0 kill @e`
`execute @a ~ ~ ~ detect ~ ~ ~ minecraft:grass snowy=false kill @e`

由于在扁平化过程中，很多方块被从多个方块状态（或称数据值）拆分为了多个方块 ID，因此不可能做到将数据值为 -1 的方块判定无损转换到单条命令内，既然解决不了那就不解决了。
